/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservartionsystemmm;

import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author NothingMeansNothing
 */
public class BusView extends javax.swing.JFrame {

    /**
     * Creates new form BusView
     */
    public BusView() {
        initComponents();
        this.setTitle("BUS VİEW ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel32 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        s7 = new javax.swing.JLabel();
        s8 = new javax.swing.JLabel();
        s9 = new javax.swing.JLabel();
        s10 = new javax.swing.JLabel();
        s11 = new javax.swing.JLabel();
        s12 = new javax.swing.JLabel();
        s13 = new javax.swing.JLabel();
        s14 = new javax.swing.JLabel();
        s18 = new javax.swing.JLabel();
        s16 = new javax.swing.JLabel();
        s15 = new javax.swing.JLabel();
        s19 = new javax.swing.JLabel();
        s20 = new javax.swing.JLabel();
        s17 = new javax.swing.JLabel();
        s22 = new javax.swing.JLabel();
        s23 = new javax.swing.JLabel();
        s24 = new javax.swing.JLabel();
        s25 = new javax.swing.JLabel();
        s26 = new javax.swing.JLabel();
        s27 = new javax.swing.JLabel();
        s28 = new javax.swing.JLabel();
        s30 = new javax.swing.JLabel();
        s21 = new javax.swing.JLabel();
        s29 = new javax.swing.JLabel();
        s32 = new javax.swing.JLabel();
        s31 = new javax.swing.JLabel();
        lblWhellPic = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        busComboBox = new javax.swing.JComboBox<>();
        busSelectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 153));
        jLabel32.setText("BUS VİEW");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s1.setBackground(new java.awt.Color(255, 255, 255));
        s1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s1.setText("1");

        s2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s2.setText("2");

        s3.setBackground(new java.awt.Color(255, 0, 0));
        s3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s3.setText("3");

        s4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s4.setText("4");

        s5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s5.setText("5");

        s6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s6.setText("6");

        s7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s7.setText("7");

        s8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s8.setText("8");

        s9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s9.setText("9");

        s10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s10.setText("10");

        s11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s11.setText("11");

        s12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s12.setText("12");

        s13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s13.setText("13");

        s14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s14.setText("14");

        s18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s18.setText("18");

        s16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s16.setText("16");

        s15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s15.setText("15");

        s19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s19.setText("19");

        s20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s20.setText("20");

        s17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s17.setText("17");

        s22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s22.setText("22");

        s23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s23.setText("23");

        s24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s24.setText("24");

        s25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s25.setText("25");

        s26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s26.setText("26");

        s27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s27.setText("27");

        s28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s28.setText("28");

        s30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s30.setText("30");

        s21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s21.setText("21");

        s29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s29.setText("29");

        s32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s32.setText("32");

        s31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/seats.png"))); // NOI18N
        s31.setText("31");

        lblWhellPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/1464269516_steering_wheel48.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/1464269645_common-logout-signout-exit-glyph.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(s17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(s21, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(s29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(s25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s26, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(s30)))))
                        .addGap(71, 71, 71)
                        .addComponent(s31, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(s1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(s11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(s15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(s19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(s23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(s27, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(s8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(s20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(s24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(s28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(s32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblWhellPic, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s12)
                            .addComponent(s16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel30)))
                        .addGap(23, 23, 23))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblWhellPic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s27, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s31, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s29, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s30, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 410, 710));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/4a4e527.mostoptions.png"))); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Name:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Surname:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Id:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("E-mail:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));
        getContentPane().add(mailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 200, 30));

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 200, 30));
        getContentPane().add(surnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 200, 30));
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 200, 30));

        busComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        getContentPane().add(busComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 140, -1));

        busSelectButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        busSelectButton.setText("Select");
        busSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busSelectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(busSelectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busSelectButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_busSelectButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusView().setVisible(true);
            }
        });
    }
    public JLabel[]getSeat(){
        JLabel[] s=new JLabel[32];
        s[0]=s1;
        s[1]=s2;
        s[2]=s3;
        s[3]=s4;
        s[4]=s5;
        s[5]=s6;
        s[6]=s7;
        s[7]=s8;
        s[8]=s9;
        s[9]=s10;
        s[10]=s11;
        s[11]=s12;
        s[12]=s13;
        s[13]=s14;
        s[14]=s15;
        s[15]=s16;
        s[16]=s17;
        s[17]=s18;
        s[18]=s19;
        s[19]=s20;
        s[20]=s21;
        s[21]=s22;
        s[22]=s23;
        s[23]=s24;
        s[24]=s25;
        s[25]=s26;
        s[26]=s27;
        s[27]=s28;
        s[28]=s29;
        s[29]=s30;
        s[30]=s31;
        s[31]=s32;                
        return s;      
    }
        
    public void busSelectSeatListener(ActionListener lis){
        busSelectButton.addActionListener(lis);
    }
    public int getSeatId(){
        return busComboBox.getSelectedIndex();
    }
    
    public String getPassengerName(){
        return nameField.getText();
    }
    
     public String getPassengerSurname(){
        return surnameField.getText();
    }
     
      public String getPassengerId(){
        return idField.getText();
    }
      
     public String getPassengerMail(){
        return mailField.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> busComboBox;
    private javax.swing.JButton busSelectButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblWhellPic;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s10;
    private javax.swing.JLabel s11;
    private javax.swing.JLabel s12;
    private javax.swing.JLabel s13;
    private javax.swing.JLabel s14;
    private javax.swing.JLabel s15;
    private javax.swing.JLabel s16;
    private javax.swing.JLabel s17;
    private javax.swing.JLabel s18;
    private javax.swing.JLabel s19;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s20;
    private javax.swing.JLabel s21;
    private javax.swing.JLabel s22;
    private javax.swing.JLabel s23;
    private javax.swing.JLabel s24;
    private javax.swing.JLabel s25;
    private javax.swing.JLabel s26;
    private javax.swing.JLabel s27;
    private javax.swing.JLabel s28;
    private javax.swing.JLabel s29;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s30;
    private javax.swing.JLabel s31;
    private javax.swing.JLabel s32;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JLabel s7;
    private javax.swing.JLabel s8;
    private javax.swing.JLabel s9;
    private javax.swing.JTextField surnameField;
    // End of variables declaration//GEN-END:variables
}
