/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservartionsystemmm;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Ayda
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    
    public View() {
        initComponents();
        returnDate.setVisible(false);
        
       this.setTitle("EA TİCKET ");
       buttonGroup1.add(yes);
       buttonGroup1.add(no);
       
       buttonGroup2.add(yesTv);
       buttonGroup2.add(noTv);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        ticketView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exit1HomePage = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fromBox1 = new javax.swing.JComboBox<>();
        label32 = new javax.swing.JLabel();
        toBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        oneWay = new javax.swing.JRadioButton();
        RoundTrip = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passengersBox = new javax.swing.JComboBox<>();
        journeyDate = new com.toedter.calendar.JDateChooser();
        returnDate = new com.toedter.calendar.JDateChooser();
        managerButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        managerLogin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loginUser = new javax.swing.JTextField();
        loginPassword = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        backtoTicketView = new javax.swing.JButton();
        busView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        backToTicketView = new javax.swing.JButton();
        updatePage = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        updateName = new javax.swing.JTextField();
        updateTimeHour = new javax.swing.JComboBox<>();
        jLabel73 = new javax.swing.JLabel();
        updateTimeMin = new javax.swing.JComboBox<>();
        updateFrom = new javax.swing.JComboBox<>();
        updateTo = new javax.swing.JComboBox<>();
        updateYesWir = new javax.swing.JRadioButton();
        updateNoWir = new javax.swing.JRadioButton();
        updateYesTv = new javax.swing.JRadioButton();
        updateNoTv = new javax.swing.JRadioButton();
        updateButton_2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        updateJourney = new com.toedter.calendar.JDateChooser();
        updateReturn = new com.toedter.calendar.JDateChooser();
        managerPage = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        busNameField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fromBoxBus = new javax.swing.JComboBox<>();
        toBoxBus = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        busIdField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        yesTv = new javax.swing.JRadioButton();
        noTv = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        busTable = new javax.swing.JTable();
        timeHour = new javax.swing.JComboBox<>();
        timeMin = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        backToManagerLogin = new javax.swing.JButton();
        dateOfJourney = new com.toedter.calendar.JDateChooser();
        dateOfReturn = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        ticketView.setBackground(new java.awt.Color(204, 204, 255));
        ticketView.setForeground(new java.awt.Color(255, 255, 102));
        ticketView.setDoubleBuffered(false);
        ticketView.setEnabled(false);
        ticketView.setName("ticket\n"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("EA TİCKET");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/bus-icon.png"))); // NOI18N

        exit1HomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/Exit.png"))); // NOI18N
        exit1HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1HomePageActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("To:");

        fromBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul(Anadolu)", "Istanbul(Avrupa)", "Izmir", "Ankara", "Bursa", "Adana ", "Antalya", "Bodrum", "Mersin" }));
        fromBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromBox1ActionPerformed(evt);
            }
        });

        label32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label32.setText("From:");

        toBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul(Anadolu)", "Istanbul(Avrupa)", "Izmir", "Ankara", "Bursa", "Adana ", "Antalya", "Bodrum", "Mersin" }));
        toBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Bus Search:");

        oneWay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneWay.setText("One Way");

        RoundTrip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RoundTrip.setText("Round Trip");
        RoundTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundTripActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Date Of Journey:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Date Of Return:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Passengers:");

        passengersBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        passengersBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengersBoxActionPerformed(evt);
            }
        });

        journeyDate.setName("journeyDate"); // NOI18N

        returnDate.setName("returnDate"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passengersBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(oneWay))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label32)
                                .addGap(24, 24, 24)
                                .addComponent(fromBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(toBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RoundTrip)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(journeyDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(returnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label32)
                    .addComponent(jLabel4)
                    .addComponent(toBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(oneWay)
                    .addComponent(RoundTrip))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(journeyDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passengersBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        managerButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        managerButton.setForeground(new java.awt.Color(0, 0, 204));
        managerButton.setText("Manager Login");
        managerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButtonActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 0, 153));
        searchButton.setText("Search Buses");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ticketViewLayout = new javax.swing.GroupLayout(ticketView);
        ticketView.setLayout(ticketViewLayout);
        ticketViewLayout.setHorizontalGroup(
            ticketViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketViewLayout.createSequentialGroup()
                .addGroup(ticketViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketViewLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(ticketViewLayout.createSequentialGroup()
                        .addGroup(ticketViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ticketViewLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(managerButton)
                                .addGap(61, 61, 61)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ticketViewLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)))
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ticketViewLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(exit1HomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ticketViewLayout.setVerticalGroup(
            ticketViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketViewLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ticketViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketViewLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ticketViewLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(ticketViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(exit1HomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(ticketView, "card2");

        managerLogin.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Manager Login");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/11.png"))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("User Name:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Password:");

        loginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 0, 153));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginUser)
                    .addComponent(loginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/Exit.png"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        backtoTicketView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/back-icone-9284-48.png"))); // NOI18N
        backtoTicketView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoTicketViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout managerLoginLayout = new javax.swing.GroupLayout(managerLogin);
        managerLogin.setLayout(managerLoginLayout);
        managerLoginLayout.setHorizontalGroup(
            managerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerLoginLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(backtoTicketView, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(managerLoginLayout.createSequentialGroup()
                .addGroup(managerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerLoginLayout.createSequentialGroup()
                        .addContainerGap(112, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(managerLoginLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        managerLoginLayout.setVerticalGroup(
            managerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerLoginLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(managerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(managerLoginLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))
                    .addGroup(managerLoginLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(managerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backtoTicketView)
                    .addComponent(exitButton))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        getContentPane().add(managerLogin, "card3");

        busView.setBackground(new java.awt.Color(204, 204, 255));

        searchTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Time Hour", "Time Minute", "From", "To", "Journey Date", "Return Date", "Wireless", "Tv"
            }
        ));
        jScrollPane1.setViewportView(searchTable);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("BUS SCHEDULES");

        selectButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectButton.setText("SELECT");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        backToTicketView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/back-icone-9284-48.png"))); // NOI18N
        backToTicketView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToTicketViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busViewLayout = new javax.swing.GroupLayout(busView);
        busView.setLayout(busViewLayout);
        busViewLayout.setHorizontalGroup(
            busViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busViewLayout.createSequentialGroup()
                .addGroup(busViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(busViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(busViewLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 297, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToTicketView, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(busViewLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        busViewLayout.setVerticalGroup(
            busViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busViewLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(backToTicketView, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(busView, "card5");

        updatePage.setBackground(new java.awt.Color(204, 204, 255));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setText("Bus Name:");

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setText("Timing:");

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel67.setText("From:");

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel68.setText("To:");

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel69.setText("Wireless:");

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel70.setText("TV:");

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel71.setText("Date of Journey:");

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel72.setText("Date of return:");

        updateTimeHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        updateTimeHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTimeHourActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel73.setText(":");

        updateTimeMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        updateTimeMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTimeMinActionPerformed(evt);
            }
        });

        updateFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul(Anadolu)", "Istanbul(Avrupa)", "Izmir", "Ankara", "Bursa", "Adana ", "Antalya", "Bodrum", "Mersin" }));
        updateFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFromActionPerformed(evt);
            }
        });

        updateTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul(Anadolu)", "Istanbul(Avrupa)", "Izmir", "Ankara", "Bursa", "Adana ", "Antalya", "Bodrum", "Mersin" }));
        updateTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateToActionPerformed(evt);
            }
        });

        updateYesWir.setText("Yes");

        updateNoWir.setText("No");

        updateYesTv.setText("Yes");

        updateNoTv.setText("No");

        updateButton_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton_2.setText("UPDATE");
        updateButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton_2ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/back-icone-9284-48.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Update Page");

        javax.swing.GroupLayout updatePageLayout = new javax.swing.GroupLayout(updatePage);
        updatePage.setLayout(updatePageLayout);
        updatePageLayout.setHorizontalGroup(
            updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePageLayout.createSequentialGroup()
                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePageLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatePageLayout.createSequentialGroup()
                                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateTimeMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updatePageLayout.createSequentialGroup()
                                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel69)
                                    .addComponent(jLabel70))
                                .addGap(31, 31, 31)
                                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updatePageLayout.createSequentialGroup()
                                        .addComponent(updateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(updateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(updatePageLayout.createSequentialGroup()
                                        .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(updateYesWir)
                                            .addComponent(updateYesTv))
                                        .addGap(71, 71, 71)
                                        .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(updateNoTv)
                                            .addComponent(updateNoWir)))))
                            .addGroup(updatePageLayout.createSequentialGroup()
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updatePageLayout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addGap(34, 34, 34)
                                .addComponent(updateJourney, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updatePageLayout.createSequentialGroup()
                                .addComponent(jLabel72)
                                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updatePageLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(updateButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(updatePageLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(updateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(updatePageLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        updatePageLayout.setVerticalGroup(
            updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePageLayout.createSequentialGroup()
                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePageLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updatePageLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(updateName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTimeMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(updateYesWir)
                    .addComponent(updateNoWir))
                .addGap(29, 29, 29)
                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(updateYesTv)
                    .addComponent(updateNoTv))
                .addGap(30, 30, 30)
                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(updateJourney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(updatePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(updateButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        getContentPane().add(updatePage, "card8");

        managerPage.setBackground(new java.awt.Color(204, 204, 255));
        managerPage.setForeground(new java.awt.Color(204, 204, 255));
        managerPage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("EA TICKET");

        deleteButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        deleteButton.setText("Delete Buses");

        updateButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        updateButton.setText("Update Bus");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Bus Name:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Bus ID:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("From:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Timing:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("To:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText(":");

        fromBoxBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul(Anadolu)", "Istanbul(Avrupa)", "Izmir", "Ankara", "Bursa", "Adana ", "Antalya", "Bodrum", "Mersin" }));
        fromBoxBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromBoxBusActionPerformed(evt);
            }
        });

        toBoxBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul(Anadolu)", "Istanbul(Avrupa)", "Izmir", "Ankara", "Bursa", "Adana ", "Antalya", "Bodrum", "Mersin" }));
        toBoxBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBoxBusActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("BUSES");

        addButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        addButton.setText("Add Buses");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Wireless:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("TV:");

        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setText("No");

        yesTv.setText("Yes");

        noTv.setText("No");

        busTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        busTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus ID", "Bus Name", "Hour", "Minute", "From", "To", "Journey Date", "Return Date", "Wireless", "Tv"
            }
        ));
        jScrollPane2.setViewportView(busTable);

        timeHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        timeHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeHourActionPerformed(evt);
            }
        });

        timeMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        timeMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeMinActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Date of Journey:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Date of return:");

        backToManagerLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservartionsystemmm/back-icone-9284-48.png"))); // NOI18N
        backToManagerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToManagerLoginActionPerformed(evt);
            }
        });

        dateOfJourney.setName("dateOfJourney"); // NOI18N

        dateOfReturn.setName("dateOfReturn"); // NOI18N

        javax.swing.GroupLayout managerPageLayout = new javax.swing.GroupLayout(managerPage);
        managerPage.setLayout(managerPageLayout);
        managerPageLayout.setHorizontalGroup(
            managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerPageLayout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(managerPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(managerPageLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(managerPageLayout.createSequentialGroup()
                .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerPageLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)))
                .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerPageLayout.createSequentialGroup()
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managerPageLayout.createSequentialGroup()
                                .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, managerPageLayout.createSequentialGroup()
                                        .addComponent(timeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(timeMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fromBoxBus, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toBoxBus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(busIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(managerPageLayout.createSequentialGroup()
                                .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yes)
                                    .addComponent(yesTv))
                                .addGap(31, 31, 31)
                                .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noTv)
                                    .addComponent(no)))
                            .addComponent(busNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backToManagerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addComponent(jLabel23))
                    .addGroup(managerPageLayout.createSequentialGroup()
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateOfJourney, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(dateOfReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        managerPageLayout.setVerticalGroup(
            managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerPageLayout.createSequentialGroup()
                .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerPageLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(busIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(busNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeHour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromBoxBus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toBoxBus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(yes)
                            .addComponent(no))
                        .addGap(18, 18, 18)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(yesTv)
                            .addComponent(noTv))
                        .addGap(38, 38, 38)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(dateOfJourney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(managerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(managerPageLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(backToManagerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23))
        );

        getContentPane().add(managerPage, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromBox1ActionPerformed

    private void RoundTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundTripActionPerformed
        // TODO add your handling code here:
     
        if(RoundTrip.isSelected()){
             dateOfReturn.setVisible(true);
        }
        else{
             dateOfReturn.setVisible(false);
        }
       
    }//GEN-LAST:event_RoundTripActionPerformed

    private void managerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButtonActionPerformed

      managerLogin.setVisible(true);
      ticketView.setVisible(false);
    }//GEN-LAST:event_managerButtonActionPerformed

    private void exit1HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1HomePageActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit1HomePageActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
      
       
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void toBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toBoxActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backtoTicketViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoTicketViewActionPerformed

        // TODO add your handling code here:
        managerLogin.setVisible(false);
        ticketView.setVisible(true);
    }//GEN-LAST:event_backtoTicketViewActionPerformed

    private void backToTicketViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToTicketViewActionPerformed

       busView.setVisible(false);
       ticketView.setVisible(true);
    }//GEN-LAST:event_backToTicketViewActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed

     
    }//GEN-LAST:event_selectButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

       System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void busSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busSelectButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_busSelectButtonActionPerformed

    private void updateTimeHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTimeHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTimeHourActionPerformed

    private void updateTimeMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTimeMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTimeMinActionPerformed

    private void updateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateFromActionPerformed

    private void updateToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateToActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButton_2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updatePage.setVisible(false);
        managerPage.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

    }//GEN-LAST:event_updateButtonActionPerformed

    private void fromBoxBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromBoxBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromBoxBusActionPerformed

    private void toBoxBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBoxBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toBoxBusActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
        if(yes.isSelected()){
            no.isSelected();
        }
    }//GEN-LAST:event_yesActionPerformed

    private void timeHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeHourActionPerformed

    private void timeMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeMinActionPerformed

    private void backToManagerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToManagerLoginActionPerformed

        managerPage.setVisible(false);
       // managerLogin.setVisible(true);
    }//GEN-LAST:event_backToManagerLoginActionPerformed

    private void passengersBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengersBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengersBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    //ticketVİew

    public JPanel getBusView() {
        return busView;
    }

    public void setBusView(JPanel busView) {
        this.busView = busView;
    }

    public JPanel getTicketView() {
        return ticketView;
    }

    public void setTicketView(JPanel ticketView) {
        this.ticketView = ticketView;
    }
    
    public String getFrom(){
        return (String) fromBox1.getSelectedItem();
    }
    
    public String getTo(){
        return (String) toBox.getSelectedItem();
    }
    
    public boolean isSelectedOneWay(){
        return oneWay.isSelected();
    }
    
    public boolean isSelectedRoundTrip(){
        return RoundTrip.isSelected();
    }
    
    public String getDateOfJourney(){
        if(dateOfJourney.getDate()==null){            
            return "NULL";
        }else{
            SimpleDateFormat dateformat=new SimpleDateFormat("dd-MM-yyyy");
        return dateformat.format(dateOfJourney.getDate());
        }
        
    }
    
    
    public String getDateOfReturn(){
       if(dateOfReturn.getDate()==null){
            
            return "NULL";
        }else{
            SimpleDateFormat dateformat=new SimpleDateFormat("dd-MM-yyyy");
        return dateformat.format(dateOfReturn.getDate());
        }
        
    }
    
    public int getPassenger(){
        return passengersBox.getSelectedIndex()+1;
    }
    
    public void listenerButton(ActionListener a) {
        searchButton.addActionListener(a);
     
    }
        
      
    public JPanel getManagerPage(){
        return managerPage;
    }

    //managerView
    public void setManagerPage(JPanel managerPage) {
        this.managerPage = managerPage;
    }

    public int getBusId() {
        return Integer.parseInt(busIdField.getText());
    }
    
    public String getBusName(){
        return (busNameField.getText());
    }
    
    public int getTimeHour(){
        return Integer.parseInt(timeHour.getSelectedItem().toString());
    }
    
    public int getTimeMin(){
       return Integer.parseInt(timeMin.getSelectedItem().toString());
    }
    
    public String getFromBus(){
        return  fromBoxBus.getSelectedItem().toString();
    }
    
     public String getToBus(){
        return  toBoxBus.getSelectedItem().toString();
    }
    
     public  boolean getWireless()
     {
         if(yes.isSelected()){
             return true;
         }
         return false;
     }
     
      public  boolean getTv()
     {
         if(yesTv.isSelected()){
             return true;
         }
         return false;
     }
      
      public String getDateOfJourney2(){
        SimpleDateFormat dateformat=new SimpleDateFormat("dd-MM-yyyy");
        return dateformat.format(dateOfJourney.getDate());
    }
    
    
    public String getDateOfReturn2(){
        SimpleDateFormat dateformat=new SimpleDateFormat("dd-MM-yyyy");
        return dateformat.format(dateOfReturn.getDate());

    }

    public JTable getBusTable() {
        return busTable;
    }

    public void setBusTable(JTable busTable) {
        this.busTable = busTable;
    }
    
    public int getDeleteId(){
        if(busTable.getSelectedRow()==-1){
            return -1;
        }
        else{
        return Integer.parseInt( busTable.getValueAt(busTable.getSelectedRow(),0).toString());
        }
    }
    
    public int xyz(){
        return busTable.getSelectedRow();
    }
    
     public void listeneraddButton(ActionListener a) {
        addButton.addActionListener(a);
     
    }
    
       public void listenerdeleteButton(ActionListener a) {
        deleteButton.addActionListener(a);
     
    }
      public void listenerupdateButton(ActionListener a) {
        updateButton.addActionListener(a);
     
    }
       
       //bus view

    public JTable getSearchTable() {
        return searchTable;
    }

    public void setSearchTable(JTable searchTable) {
        this.searchTable = searchTable;
    }
    
    public void selectButtonListener(ActionListener listener){
        selectButton.addActionListener(listener);
    }
    //bus1

   

    
    public int getSelectBusId(){
        return Integer.parseInt(searchTable.getValueAt(searchTable.getSelectedRow(),0).toString());
    }

   
    
 
       //update page
              
    public void update_button2Listener(ActionListener listener){
        updateButton_2.addActionListener(listener);
    }
    public String getBusNameUpdate(){
        return (updateName.getText());
    }
    
    public int getTimeHourUpdate(){
        return Integer.parseInt(updateTimeHour.getSelectedItem().toString());
    }
    
    public int getTimeMinUpdate(){
       return Integer.parseInt(updateTimeMin.getSelectedItem().toString());
    }
    
    public String getFromBusUpdate(){
        return  updateFrom.getSelectedItem().toString();
    }
    
     public String getToBusUpdate(){
        return  updateTo.getSelectedItem().toString();
    }
    
     public  boolean getWirelessUpdate()
     {
         if(updateYesWir.isSelected()){
             return true;
         }
         return false;
     }
     
      public  boolean getTvUpdate()
     {
         if(updateYesTv.isSelected()){
             return true;
         }
         return false;
     }
      
      public String getDateOfJourney2Update(){
        SimpleDateFormat dateformat=new SimpleDateFormat("dd-MM-yyyy");
        return dateformat.format(updateJourney.getDate());
    }
    
    
    public String getDateOfReturn2Update(){
        SimpleDateFormat dateformat=new SimpleDateFormat("dd-MM-yyyy");
        return dateformat.format(updateReturn.getDate());

    }
    
    public int getUpdateId(){
         if(busTable.getSelectedRow()==-1){
            return -1;
        }
        else{
        return Integer.parseInt( busTable.getValueAt(busTable.getSelectedRow(),0).toString());
        }
    }

    public JPanel getUpdatePage() {
        return updatePage;
    }

    public void setUpdatePage(JPanel updatePage) {
        this.updatePage = updatePage;
    }
    
   
     //login
     public String getUsername(){
         return loginUser.getText();
     }
     public String getPassword(){
         return loginPassword.getText();
     }
      public void listenerloginButton(ActionListener a) {
        loginButton.addActionListener(a);
     
    }

    public JPanel getManagerLogin() {
        return managerLogin;
    }

    public void setManagerLogin(JPanel managerLogin) {
        this.managerLogin = managerLogin;
    }
    
  
    
   
    
       
       
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RoundTrip;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backToManagerLogin;
    private javax.swing.JButton backToTicketView;
    private javax.swing.JButton backtoTicketView;
    private javax.swing.JTextField busIdField;
    private javax.swing.JTextField busNameField;
    private javax.swing.JTable busTable;
    private javax.swing.JPanel busView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dateOfJourney;
    private com.toedter.calendar.JDateChooser dateOfReturn;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exit1HomePage;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox<String> fromBox1;
    private javax.swing.JComboBox<String> fromBoxBus;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser journeyDate;
    private javax.swing.JLabel label32;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField loginUser;
    private javax.swing.JButton managerButton;
    private javax.swing.JPanel managerLogin;
    private javax.swing.JPanel managerPage;
    private javax.swing.JRadioButton no;
    private javax.swing.JRadioButton noTv;
    private javax.swing.JRadioButton oneWay;
    private javax.swing.JComboBox<String> passengersBox;
    private com.toedter.calendar.JDateChooser returnDate;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable searchTable;
    private javax.swing.JButton selectButton;
    private javax.swing.JPanel ticketView;
    private javax.swing.JComboBox<String> timeHour;
    private javax.swing.JComboBox<String> timeMin;
    private javax.swing.JComboBox<String> toBox;
    private javax.swing.JComboBox<String> toBoxBus;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateButton_2;
    private javax.swing.JComboBox<String> updateFrom;
    private com.toedter.calendar.JDateChooser updateJourney;
    private javax.swing.JTextField updateName;
    private javax.swing.JRadioButton updateNoTv;
    private javax.swing.JRadioButton updateNoWir;
    private javax.swing.JPanel updatePage;
    private com.toedter.calendar.JDateChooser updateReturn;
    private javax.swing.JComboBox<String> updateTimeHour;
    private javax.swing.JComboBox<String> updateTimeMin;
    private javax.swing.JComboBox<String> updateTo;
    private javax.swing.JRadioButton updateYesTv;
    private javax.swing.JRadioButton updateYesWir;
    private javax.swing.JRadioButton yes;
    private javax.swing.JRadioButton yesTv;
    // End of variables declaration//GEN-END:variables
}
